SOURCES = [

    # 🇺🇿 O'ZBEKISTON
    {
        "name": "Nuz.uz",
        "url": "https://nuz.uz/feed/",
        "category": "uzbekistan",
        "country": "uzbekistan",
        "active": True,
    },
    {
        "name": "Gazeta.uz",
        "url": "https://www.gazeta.uz/ru/rss/",
        "category": "uzbekistan",
        "country": "uzbekistan",
        "active": True,
    },
    {
        "name": "KUN.UZ",
        "url": "https://kun.uz/",
        "category": "uzbekistan",
        "country": "uzbekistan",
        "type": "html",
        "active": True,
    },
    {
        "name": "Daryo",
        "url": "https://daryo.uz/",
        "category": "uzbekistan",
        "country": "uzbekistan",
        "type": "html",
        "active": True,
    },

    # 🌍 DUNYO
    {
        "name": "BBC News",
        "url": "https://feeds.bbci.co.uk/news/rss.xml",
        "category": "world",
        "country": "international",
        "active": True,
    },
    {
        "name": "BBC World",
        "url": "https://feeds.bbci.co.uk/news/world/rss.xml",
        "category": "world",
        "country": "international",
        "active": True,
    },
    {
        "name": "The Guardian World",
        "url": "https://www.theguardian.com/world/rss",
        "category": "world",
        "country": "international",
        "active": True,
    },
    {
        "name": "Al Jazeera",
        "url": "https://www.aljazeera.com/xml/rss/all.xml",
        "category": "world",
        "country": "international",
        "active": True,
    },
    {
        "name": "DW",
        "url": "https://rss.dw.com/xml/rss-en-all",
        "category": "world",
        "country": "international",
        "active": True,
    },
    {
        "name": "Euronews",
        "url": "https://www.euronews.com/rss",
        "category": "world",
        "country": "international",
        "active": True,
    },
    {
        "name": "NPR",
        "url": "https://feeds.npr.org/1001/rss.xml",
        "category": "world",
        "country": "international",
        "active": True,
    },
    {
        "name": "CNN",
        "url": "http://rss.cnn.com/rss/edition.rss",
        "category": "world",
        "country": "international",
        "active": True,
    },
    {
        "name": "Sky News",
        "url": "https://feeds.skynews.com/feeds/rss/world.xml",
        "category": "world",
        "country": "international",
        "active": True,
    },

    # 💻 TEXNOLOGIYA
    {
        "name": "BBC Technology",
        "url": "https://feeds.bbci.co.uk/news/technology/rss.xml",
        "category": "technology",
        "country": "international",
        "active": True,
    },
    {
        "name": "The Guardian Technology",
        "url": "https://www.theguardian.com/technology/rss",
        "category": "technology",
        "country": "international",
        "active": True,
    },
    {
        "name": "TechCrunch",
        "url": "https://techcrunch.com/feed/",
        "category": "technology",
        "country": "international",
        "active": True,
    },
    {
        "name": "The Verge",
        "url": "https://www.theverge.com/rss/index.xml",
        "category": "technology",
        "country": "international",
        "active": True,
    },
    {
        "name": "Ars Technica",
        "url": "https://feeds.arstechnica.com/arstechnica/index",
        "category": "technology",
        "country": "international",
        "active": True,
    },
    {
        "name": "Wired",
        "url": "https://www.wired.com/feed/rss",
        "category": "technology",
        "country": "international",
        "active": True,
    },
    {
        "name": "Engadget",
        "url": "https://www.engadget.com/rss.xml",
        "category": "technology",
        "country": "international",
        "active": True,
    },
    {
        "name": "Hacker News",
        "url": "https://news.ycombinator.com/rss",
        "category": "technology",
        "country": "international",
        "active": True,
    },
    {
        "name": "TechRadar",
        "url": "https://www.techradar.com/rss",
        "category": "technology",
        "country": "international",
        "active": True,
    },

    # 💰 IQTISODIYOT
    {
        "name": "BBC Business",
        "url": "https://feeds.bbci.co.uk/news/business/rss.xml",
        "category": "economy",
        "country": "international",
        "active": True,
    },
    {
        "name": "The Guardian Business",
        "url": "https://www.theguardian.com/business/rss",
        "category": "economy",
        "country": "international",
        "active": True,
    },
    {
        "name": "CNBC",
        "url": "https://www.cnbc.com/id/100003114/device/rss/rss.html",
        "category": "economy",
        "country": "international",
        "active": True,
    },
    {
        "name": "Business Insider",
        "url": "https://www.businessinsider.com/rss",
        "category": "economy",
        "country": "international",
        "active": True,
    },
    {
        "name": "Forbes",
        "url": "https://www.forbes.com/business/feed/",
        "category": "economy",
        "country": "international",
        "active": True,
    },
    {
        "name": "MarketWatch",
        "url": "http://feeds.marketwatch.com/marketwatch/topstories/",
        "category": "economy",
        "country": "international",
        "active": True,
    },
    {
        "name": "Yahoo Finance",
        "url": "https://finance.yahoo.com/news/rssindex",
        "category": "economy",
        "country": "international",
        "active": True,
    },

    # 🔬 FAN
    {
        "name": "BBC Science",
        "url": "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml",
        "category": "science",
        "country": "international",
        "active": True,
    },
    {
        "name": "Ars Science",
        "url": "https://feeds.arstechnica.com/arstechnica/science",
        "category": "science",
        "country": "international",
        "active": True,
    },
    {
        "name": "Nature",
        "url": "https://www.nature.com/nature.rss",
        "category": "science",
        "country": "international",
        "active": True,
    },
    {
        "name": "New Scientist",
        "url": "https://www.newscientist.com/feed/home/",
        "category": "science",
        "country": "international",
        "active": False,
    },
    {
        "name": "Scientific American",
        "url": "https://www.scientificamerican.com/platform/syndication/rss/",
        "category": "science",
        "country": "international",
        "active": True,
    },

    # ⚽ SPORT
    {
        "name": "BBC Sport",
        "url": "https://feeds.bbci.co.uk/sport/rss.xml",
        "category": "sport",
        "country": "international",
        "active": True,
    },
    {
        "name": "The Guardian Sport",
        "url": "https://www.theguardian.com/sport/rss",
        "category": "sport",
        "country": "international",
        "active": True,
    },
    {
        "name": "ESPN",
        "url": "https://www.espn.com/espn/rss/news",
        "category": "sport",
        "country": "international",
        "active": True,
    },
    {
        "name": "Sky Sports",
        "url": "https://www.skysports.com/rss/12040",
        "category": "sport",
        "country": "international",
        "active": True,
    },
    {
        "name": "CBS Sports",
        "url": "https://www.cbssports.com/rss/headlines/",
        "category": "sport",
        "country": "international",
        "active": True,
    },

    # 🎮 GAMING
    {
        "name": "Ars Gaming",
        "url": "https://feeds.arstechnica.com/arstechnica/gaming",
        "category": "gaming",
        "country": "international",
        "active": True,
    },
    {
        "name": "The Verge Gaming",
        "url": "https://www.theverge.com/games/rss/index.xml",
        "category": "gaming",
        "country": "international",
        "active": False,
    },
    {
        "name": "Engadget Gaming",
        "url": "https://www.engadget.com/gaming/rss.xml",
        "category": "gaming",
        "country": "international",
        "active": False,
    },

    # 🎬 KINO / ENTERTAINMENT
    {
        "name": "BBC Entertainment",
        "url": "https://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml",
        "category": "cinema",
        "country": "international",
        "active": True,
    },
    {
        "name": "The Guardian Culture",
        "url": "https://www.theguardian.com/culture/rss",
        "category": "cinema",
        "country": "international",
        "active": True,
    },
    {
        "name": "Wired Culture",
        "url": "https://www.wired.com/feed/category/culture/latest/rss",
        "category": "cinema",
        "country": "international",
        "active": True,
    },
]
